export const CHECK_AUTH_STATUS_REQUEST = 'CHECK_AUTH_STATUS_REQUEST'
export const CHECK_AUTH_STATUS_SUCCESS = 'CHECK_AUTH_STATUS_SUCCESS'
export const CHECK_AUTH_STATUS_FAILURE = 'CHECK_AUTH_STATUS_FAILURE'
